version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
- package-ecosystem: cargo
  directory: "/api"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  groups:
    async-graphql:
      patterns:
      - async-graphql
      - async-graphql-*
    icu:
      patterns:
      - icu_*
    sea-query:
      patterns:
      - sea-query
      - sea-query-*
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  groups:
    date-fns:
      patterns:
      - date-fns
      - "@date-fns/*"
    emotion:
      patterns:
      - "@emotion/*"
    graphql-codegen:
      patterns:
      - "@graphql-codegen/*"
    mui:
      patterns:
      - "@mui/*"
    react:
      patterns:
      - react
      - react-dom
  open-pull-requests-limit: 99
  versioning-strategy: increase
- package-ecosystem: docker
  directories:
  - "/api"
  - "/ui"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
