version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
- package-ecosystem: cargo
  directory: "/api"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  groups:
    async-graphql:
      patterns:
      - async-graphql
      - async-graphql-*
    icu:
      patterns:
      - icu
      - icu_*
    sea-query:
      patterns:
      - sea-query
      - sea-query-*
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: weekly
    day: saturday
    time: "00:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
