[package]
name = "postgres"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
test-postgres = []

[dependencies.domain]
workspace = true

[dependencies.async-trait]
version = "0.1.81"

[dependencies.chrono]
version = "0.4.38"
default-features = false
features = ["clock", "std"]

[dependencies.cow-utils]
version = "0.1.3"

[dependencies.derive_more]
version = "1.0.0"
features = ["constructor", "from", "into"]

[dependencies.futures]
version = "0.3.30"
default-features = false

[dependencies.indexmap]
version = "2.4.0"
features = ["serde"]

[dependencies.log]
version = "0.4.22"

[dependencies.sea-query]
version = "0.32.0-rc.1"
features = ["thread-safe"]

[dependencies.sea-query-binder]
version = "0.7.0-rc.1"
features = ["postgres-array", "sqlx-postgres", "with-chrono", "with-json", "with-uuid"]

[dependencies.serde]
version = "1.0.208"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.125"

[dependencies.serde_with]
version = "3.9.0"

[dependencies.sqlx]
version = "0.8.0"
features = ["chrono", "json", "postgres", "runtime-tokio", "tls-native-tls", "uuid"]

[dependencies.sqlx_migrator]
version = "0.15.0"
features = ["postgres"]

[dependencies.uuid]
version = "1.10.0"

[dev-dependencies.include_dir]
version = "0.7.4"

[dev-dependencies.pretty_assertions]
version = "1.3.0"
features = ["unstable"]

[dev-dependencies.test-context]
version = "0.3.0"

[dev-dependencies.tokio]
version = "1.39.2"
features = ["macros", "rt-multi-thread"]
