[package]
name = "postgres"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
test-postgres = []

[dependencies.domain]
workspace = true

[dependencies.async-trait]
version = "0.1.80"

[dependencies.chrono]
version = "0.4.38"
default-features = false
features = ["clock", "std"]

[dependencies.cow-utils]
version = "0.1.3"

[dependencies.derive_more]
version = "0.99.17"

[dependencies.futures]
version = "0.3.30"
default-features = false

[dependencies.indexmap]
version = "2.2.6"
features = ["serde"]

[dependencies.log]
version = "0.4.21"

[dependencies.sea-query]
version = "0.30.7"
features = ["thread-safe"]

[dependencies.sea-query-binder]
version = "0.5.0"
features = ["postgres-array", "sqlx-postgres", "with-chrono", "with-json", "with-uuid"]

[dependencies.serde]
version = "1.0.198"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.116"

[dependencies.serde_with]
version = "3.8.1"

[dependencies.sqlx]
version = "0.7.4"
features = ["chrono", "json", "postgres", "runtime-tokio", "tls-native-tls", "uuid"]

[dependencies.sqlx_migrator]
version = "0.14.0"
features = ["postgres"]

[dependencies.uuid]
version = "1.8.0"

[dev-dependencies.include_dir]
version = "0.7.3"
features = ["glob"]

[dev-dependencies.pretty_assertions]
version = "1.3.0"
features = ["unstable"]

[dev-dependencies.test-context]
version = "0.3.0"

[dev-dependencies.tokio]
version = "1.37.0"
features = ["macros", "rt-multi-thread"]
