[package]
name = "postgres"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
test-postgres = []

[dependencies.domain]
workspace = true

[dependencies.anyhow]
version = "1.0.75"

[dependencies.async-trait]
version = "0.1.74"

[dependencies.chrono]
version = "0.4.31"
default-features = false
features = ["clock", "std"]

[dependencies.cow-utils]
version = "0.1.3"

[dependencies.derive_more]
version = "0.99.17"

[dependencies.futures]
version = "0.3.29"
default-features = false

[dependencies.indexmap]
version = "2.1.0"
features = ["serde"]

[dependencies.sea-query]
version = "0.30.5"
features = ["thread-safe"]

[dependencies.sea-query-binder]
version = "0.5.0"
features = ["postgres-array", "sqlx-postgres", "with-chrono", "with-json", "with-uuid"]

[dependencies.serde]
version = "1.0.193"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.108"

[dependencies.sqlx]
version = "0.7.3"
features = ["chrono", "json", "postgres", "runtime-tokio", "tls-rustls", "uuid"]

[dependencies.thiserror]
version = "1.0.51"

[dependencies.uuid]
version = "1.6.1"

[dev-dependencies.include_dir]
version = "0.7.3"
features = ["glob"]

[dev-dependencies.pretty_assertions]
version = "1.3.0"

[dev-dependencies.test-context]
version = "0.1.4"

[dev-dependencies.tokio]
version = "1.35.0"
features = ["macros", "rt-multi-thread"]
