[package]
name = "postgres"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
test-postgres = []

[dependencies.domain]
workspace = true

[dependencies.anyhow]
version = "1.0.71"

[dependencies.async-trait]
version = "0.1.68"

[dependencies.chrono]
version = "0.4.26"
default-features = false
features = ["clock", "std"]

[dependencies.derive_more]
version = "0.99.17"

[dependencies.futures]
version = "0.3.28"
default-features = false

[dependencies.indexmap]
version = "2.0.0"
features = ["serde"]

[dependencies.sea-query]
version = "0.28.5"
features = ["thread-safe"]

[dependencies.sea-query-binder]
version = "0.3.1"
features = ["postgres-array", "sqlx-postgres", "with-chrono", "with-json", "with-uuid"]

[dependencies.serde]
version = "1.0.169"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.102"

[dependencies.sqlx]
version = "0.6.3"
features = ["chrono", "json", "postgres", "runtime-tokio-rustls", "tls", "uuid"]

[dependencies.thiserror]
version = "1.0.40"

[dependencies.uuid]
version = "1.4.0"

[dev-dependencies.include_dir]
version = "0.7.3"
features = ["glob"]

[dev-dependencies.pretty_assertions]
version = "1.3.0"

[dev-dependencies.test-context]
version = "0.1.4"

[dev-dependencies.tokio]
version = "1.29.0"
features = ["macros", "rt-multi-thread"]
