fragment externalServiceNode on ExternalService {
  id
  slug
  kind
  name
  baseUrl
  urlPattern
}

fragment sourceNode on Source {
  id
  externalService {
    ...externalServiceNode
  }
  externalMetadata
  url
  createdAt
  updatedAt
}

query Source($externalServiceID: UUID!, $externalMetadata: ExternalMetadataInput!) {
  source(externalServiceId: $externalServiceID, externalMetadata: $externalMetadata) {
    ...sourceNode
  }
}
