fragment mediumNode on Medium {
  id
  replicas {
    ...replicaNode
  }
  createdAt
  updatedAt
}

fragment replicaNode on Replica {
  id
  displayOrder
  thumbnail {
    id
    width
    height
    url
    createdAt
    updatedAt
  }
  originalUrl
  url
  mimeType
  width
  height
  status {
    phase
  }
  createdAt
  updatedAt
}

query AllMedia($number: Int!, $after: String, $sourceIDs: [UUID!], $tagTagTypeIDs: [TagTagTypeInput!]) {
  allMedia(first: $number, after: $after, sourceIds: $sourceIDs, tagIds: $tagTagTypeIDs, order: DESC) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...mediumNode
      }
    }
  }
}
