[config]
skip_core_tasks = true

[tasks.coverage]
workspace = false
description = "Test with coverage"
script = '''
#!/usr/bin/env bash
set -euo pipefail

source scripts/setup-postgres.bash
cargo tarpaulin "$@"
'''

[tasks.test]
workspace = false
description = "Test"
script = '''
#!/usr/bin/env bash
set -euo pipefail

source scripts/setup-postgres.bash
cargo test "$@"
'''
