name: CI Workflow
on:
  - push

jobs:
  api-test:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make
      - name: Run tests
        working-directory: api
        run: |
          cargo make test --workspace
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
