name: Dependencies Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 5'

defaults:
  run:
    shell: bash

jobs:
  yarn:
    uses: ./.github/workflows/_update-yarn.yml
    with:
      directory: /ui
    secrets:
      GH_TOKEN: ${{ secrets.PAT }}
